name       : btrbk
version    : 0.31.2
release    : 1
source     :
    - https://github.com/digint/btrbk/archive/refs/tags/v0.31.2.tar.gz : 3eeed69dc1c7bbf15c467ca3900e8db8644206c707c78eb8f664c17e37650133
license    : GPL-3.0-or-later
component  : system.utils
summary    : Tool for creating snapshots and remote backups of btrfs subvolumes
description: |
    btrbk is a backup tool for btrfs subvolumes, taking advantage of btrfs specific capabilities to create atomic snapshots and transfer them incrementally to your backup locations.
builddeps  :
    - asciidoctor
rundeps    :
    - perl
build      : |
    %make
install    : |
    %make_install CONFDIR=/usr/share
    rm -rf $installdir/usr/share/doc
