name       : btrbk
version    : 0.32.4
release    : 5
source     :
    - https://github.com/digint/btrbk/archive/refs/tags/v0.32.4.tar.gz : 4bb49af90c36ed2aed6d887559518f11d7d98bacb2f5982449fcf4fc5d20c80a
license    : GPL-3.0-or-later
component  : system.utils
summary    : Tool for creating snapshots and remote backups of btrfs subvolumes
description: |
    btrbk is a backup tool for btrfs subvolumes, taking advantage of btrfs specific capabilities to create atomic snapshots and transfer them incrementally to your backup locations.
builddeps  :
    - asciidoctor
rundeps    :
    - perl
build      : |
    %make
install    : |
    %make_install CONFDIR=/usr/share
    rm -rf $installdir/usr/share/doc
